CREATE TABLE IF NOT EXISTS TASK_GROUPS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL UNIQUE,
    STATUS     VARCHAR(20) DEFAULT 'OPEN',
    CREATED_AT TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 100;
