CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID BIGINT NOT NULL ,
    ROLE_ID BIGINT NOT NULL ,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ,
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);