CREATE TABLE IF NOT EXISTS TASKS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE          VARCHAR(255) NOT NULL,
    DESCRIPTION    TEXT,
    STATUS         VARCHAR(20) DEFAULT 'TODO',
    CREATED_AT     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY_ID  BIGINT       NULL,
    ASSIGNED_TO_ID BIGINT       NULL,
    TASK_GROUP_ID  BIGINT       NULL,
    CONSTRAINT FK_TASK_CREATED_BY FOREIGN KEY (CREATED_BY_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
    CONSTRAINT FK_TASK_ASSIGNED_TO FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
    CONSTRAINT FK_TASK_GROUP_ID FOREIGN KEY (TASK_GROUP_ID) REFERENCES TASK_GROUPS (ID) ON DELETE SET NULL
) AUTO_INCREMENT = 100;